[ftplugin]
python = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal textwidth=100
setlocal foldmethod=indent
setlocal conceallevel=0
'''

c = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal foldmethod=syntax
setlocal expandtab
setlocal textwidth=80
nnoremap <buffer> ,x  <Cmd>QuickRun make/src<CR>
nnoremap <buffer> ,,x <Cmd>QuickRun cmake/src<CR>
setlocal conceallevel=0
'''

cpp = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal foldmethod=syntax
setlocal expandtab
setlocal textwidth=80
nnoremap <buffer> ,x  <Cmd>QuickRun make/src<CR>
nnoremap <buffer> ,,x <Cmd>QuickRun cmake/src<CR>
setlocal conceallevel=0
'''

go = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal formatoptions+r
setlocal foldmethod=indent
setlocal conceallevel=0
'''

tex = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal foldmethod=indent
setlocal expandtab
setlocal wrap
setlocal conceallevel=0
'''

html = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal iskeyword+=-
setlocal foldmethod=indent
setlocal conceallevel=0
'''

css = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal iskeyword+=-
setlocal foldmethod=indent
setlocal conceallevel=0
'''

vim = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal foldmethod=indent
setlocal conceallevel=0
'''

javascript = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal foldmethod=indent
setlocal conceallevel=0
'''

csv = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal nowrap
imap , ,
setlocal conceallevel=0
'''

text = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal conceallevel=0
'''

help = '''
setlocal noet
setlocal foldmethod=indent
setlocal conceallevel=0
'''

markdown = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal wrap
nnoremap <buffer> ,x  <Cmd>QuickRun markdown/marp<CR>
nnoremap <buffer> ,,x <Cmd>QuickRun markdown/marp-pdf<CR>
setlocal conceallevel=0
'''

vue = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal iskeyword+=-
setlocal foldmethod=indent
setlocal conceallevel=0
'''

json = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal foldmethod=indent
setlocal conceallevel=0
'''

lua = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal foldmethod=indent
setlocal conceallevel=0
'''

NvimTree = '''
nmap <buffer> >  <Cmd>NvimTreeResize +10<CR>
nmap <buffer> <  <Cmd>NvimTreeResize -10<CR>
'''

tagbar = '''
function! s:tagbar_width_plus()
  let g:tagbar_width = g:tagbar_width + 10
endfunction

function! s:tagbar_width_minus()
  let g:tagbar_width = g:tagbar_width - 10
endfunction

command! TagbarWidthPlus  call s:tagbar_width_plus()
command! TagbarWidthMinus call s:tagbar_width_minus()

nmap <buffer> <   <Cmd>TagbarToggle<CR>:TagbarWidthPlus<CR>:TagbarToggle<CR>sl
nmap <buffer> >   <Cmd>TagbarToggle<CR>:TagbarWidthMinus<CR>:TagbarToggle<CR>sl
'''
